/*
  THETE AGRO IMPEX — CENTRALIZED PRODUCT CATALOGUE
  ------------------------------------------------
  To add or edit products, change entries below only.
  Each product needs: id, slug, name, category, shortDescription, description,
  image (main), thumb (optional square crop), specifications (array),
  origin, packaging, availability, tags and keywords (used by search).
  Detail pages are served at /products/<slug> (see netlify.toml / server.js).
*/
const CATEGORIES = [
  'Fruits',
  'Vegetables',
  'Rice',
  'Pulses & Dals',
  'Spices',
  'Other Agro Products'
];

const PRODUCTS_DATA = [
  {
    id: 'orchard-fruits',
    slug: 'orchard-fruits',
    name: 'Orchard Fruits',
    category: 'Fruits',
    tag: 'Seasonal',
    image: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&w=1000&q=85',
    thumb: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&w=400&q=80',
    shortDescription: 'Bright, seasonal and full of character — selected from trusted Indian orchards.',
    description: 'Premium export varieties including Bhagwa pomegranates, table grapes and seasonal mangoes, carefully harvested at optimum maturity and pre-cooled before packing. Each lot is graded for size, colour and brix before dispatch.',
    specifications: ['Graded by size and colour', 'Pre-cooled and packed in ventilated cartons', 'Availability follows seasonal harvest windows'],
    origin: 'Maharashtra Orchards',
    packaging: 'Ventilated export cartons, buyer-specified net weights',
    availability: 'Seasonal',
    keywords: ['pomegranate', 'bhagwa', 'grapes', 'mango', 'fruit exporter india']
  },
  {
    id: 'field-vegetables',
    slug: 'field-vegetables',
    name: 'Field Vegetables',
    category: 'Vegetables',
    tag: 'Farm fresh',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=1000&q=85',
    thumb: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=400&q=80',
    shortDescription: 'Graded and packed for freshness, consistency and a dependable arrival.',
    description: 'Export-grade produce from the Nashik belt — onions, tomatoes, green chillies, ginger and garlic — sorted by size and maturity, and packed for dependable shelf life on arrival.',
    specifications: ['Size-graded and hand sorted', 'Cured onions for long transit', 'Buyer-specified grade mix'],
    origin: 'Nashik & Regional Farms',
    packaging: 'Mesh bags / cartons as per buyer specification',
    availability: 'Year round (variety dependent)',
    keywords: ['onion', 'nashik onion', 'tomato', 'garlic', 'ginger', 'vegetable exporter india']
  },
  {
    id: 'dals-pulses',
    slug: 'dals-pulses',
    name: 'Dals & Pulses',
    category: 'Pulses & Dals',
    tag: 'Pantry staples',
    image: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=1000&q=85',
    thumb: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=400&q=80',
    shortDescription: 'Reliable lentils, chickpeas and pulses with consistent grading.',
    description: 'Machine-cleaned and sortexed toor dal, chana dal, moong beans, kabuli and desi chickpeas, and urad — delivered with consistent moisture and purity levels, supported by lot-wise quality checks.',
    specifications: ['Sortex cleaned', 'Moisture and purity as per contract', 'Lot-wise quality documentation'],
    origin: 'Central & Western India',
    packaging: '25 / 50 kg PP bags or jumbo bags',
    availability: 'Year round',
    keywords: ['toor dal', 'chana dal', 'moong', 'chickpeas', 'kabuli chana', 'urad', 'pulses exporter india']
  },
  {
    id: 'premium-rice',
    slug: 'premium-rice',
    name: 'Premium Rice',
    category: 'Rice',
    tag: 'Export grade',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=1000&q=85',
    thumb: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=400&q=80',
    shortDescription: 'Basmati and non-basmati varieties, prepared for global buyers.',
    description: 'Aromatic 1121 traditional and Pusa basmati, golden sella, steam basmati and premium non-basmati long-grain rice, milled and sorted at certified mills with custom packaging options.',
    specifications: ['Sortex cleaned, silk polished on request', 'Average grain length as per variety', 'Custom private-label packaging available'],
    origin: 'Certified Indian Mills',
    packaging: '5–50 kg PP / non-woven / jute bags, buyer brand on request',
    availability: 'Year round',
    keywords: ['basmati', '1121 basmati', 'pusa', 'golden sella', 'steam rice', 'non basmati', 'rice exporter india']
  },
  {
    id: 'food-ingredients',
    slug: 'food-ingredients',
    name: 'Food Ingredients',
    category: 'Spices',
    tag: 'Made to order',
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=1000&q=85',
    thumb: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=400&q=80',
    shortDescription: 'Spices, grains and custom requirements for wholesalers, processors and food makers.',
    description: 'Whole and ground spices — turmeric fingers, red chillies, cumin and coriander seeds — along with oilseeds and grains, tailored to buyer specifications for grade, mesh size and packing.',
    specifications: ['ASTA / curcumin content on request', 'Whole, ground or powder form', 'Steam sterilization available on request'],
    origin: 'Direct Agro Processors',
    packaging: '25 / 50 kg bags or buyer-specified retail packs',
    availability: 'Year round',
    keywords: ['turmeric', 'red chilli', 'cumin', 'coriander', 'oilseeds', 'spice exporter india']
  },
  {
    id: 'green-chillies',
    slug: 'green-chillies',
    name: 'Green Chillies',
    category: 'Vegetables',
    tag: 'Farm fresh',
    image: 'https://images.unsplash.com/photo-1583258292688-d0213dc5a3a8?auto=format&fit=crop&w=1000&q=85',
    thumb: 'https://images.unsplash.com/photo-1583258292688-d0213dc5a3a8?auto=format&fit=crop&w=400&q=80',
    shortDescription: 'Fresh green chillies graded for length, colour and pungency.',
    description: 'Fresh green chillies sourced from Maharashtra growers, graded for length and colour and packed in ventilated packs to hold freshness through transit.',
    specifications: ['Graded by length and colour', 'Ventilated packing for freshness'],
    origin: 'Maharashtra & Regional Farms',
    packaging: 'Ventilated cartons / mesh bags',
    availability: 'Seasonal peaks, variety dependent',
    keywords: ['green chilli', 'chilli exporter', 'fresh chillies india']
  },
  {
    id: 'onion',
    slug: 'onion',
    name: 'Nashik Onion',
    category: 'Vegetables',
    tag: 'Export grade',
    image: 'https://images.unsplash.com/photo-1580201092675-a0a6a6cafbb1?auto=format&fit=crop&w=1000&q=85',
    thumb: 'https://images.unsplash.com/photo-1580201092675-a0a6a6cafbb1?auto=format&fit=crop&w=400&q=80',
    shortDescription: 'Cured Nashik red onions, size-graded for long-haul shipments.',
    description: 'Red onions from the Nashik belt, properly cured and graded (45–55 mm, 55–65 mm and larger), packed for reefer and dry container shipments.',
    specifications: ['Cured skins for long transit', 'Common grades: 45–55 mm, 55–65 mm, 65 mm+', 'Reefer-friendly packing'],
    origin: 'Nashik, Maharashtra',
    packaging: '5–50 kg mesh bags, jumbo bags on request',
    availability: 'Year round (variety dependent)',
    keywords: ['onion', 'red onion', 'nashik onion', 'laser onion', 'onion exporter india']
  },
  {
    id: 'potato',
    slug: 'potato',
    name: 'Potato',
    category: 'Vegetables',
    tag: 'Farm fresh',
    image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=1000&q=85',
    thumb: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=400&q=80',
    shortDescription: 'Firm table-grade potatoes graded by size and specific gravity.',
    description: 'Table-grade potatoes graded by size with consistent specific gravity, sourced from cold-chain backed stores for round-the-year supply.',
    specifications: ['Size-graded table stock', 'Cold-store sourcing for round-the-year supply'],
    origin: 'Regional cold-chain partners',
    packaging: '25 / 50 kg mesh bags, jumbo bags on request',
    availability: 'Year round',
    keywords: ['potato', 'table potato', 'potato exporter india']
  },
  {
    id: 'tomato',
    slug: 'tomato',
    name: 'Tomato',
    category: 'Vegetables',
    tag: 'Farm fresh',
    image: 'https://images.unsplash.com/photo-1546094096-0df4bcaaa337?auto=format&fit=crop&w=1000&q=85',
    thumb: 'https://images.unsplash.com/photo-1546094096-0df4bcaaa337?auto=format&fit=crop&w=400&q=80',
    shortDescription: 'Firm, uniformly ripe tomatoes graded for processing or fresh use.',
    description: 'Firm tomatoes graded for uniform ripeness, suitable for fresh consumption and supplied in breathing packing to retain quality in transit.',
    specifications: ['Uniform ripeness grading', 'Breathing packing for transit'],
    origin: 'Maharashtra & Regional Farms',
    packaging: 'Ventilated cartons / crates',
    availability: 'Seasonal peaks',
    keywords: ['tomato', 'fresh tomato', 'tomato exporter india']
  },
  {
    id: 'pomegranate',
    slug: 'pomegranate',
    name: 'Bhagwa Pomegranate',
    category: 'Fruits',
    tag: 'Seasonal',
    image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=1000&q=85',
    thumb: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80',
    shortDescription: 'Deep-aril Bhagwa pomegranates graded by count and colour.',
    description: 'Bhagwa pomegranates from Maharashtra orchards, graded by fruit count per box with deep aril colour, packed in export cartons with liners.',
    specifications: ['Graded by count per carton', 'Deep aril colour selection', 'Export cartons with liners'],
    origin: 'Maharashtra Orchards',
    packaging: '3–5 kg export cartons with liners',
    availability: 'Seasonal (main window Sep–Feb)',
    keywords: ['pomegranate', 'bhagwa', 'anar exporter india']
  },
  {
    id: 'table-grapes',
    slug: 'table-grapes',
    name: 'Table Grapes',
    category: 'Fruits',
    tag: 'Seasonal',
    image: 'https://images.unsplash.com/photo-1537640538966-79f369143f8f?auto=format&fit=crop&w=1000&q=85',
    thumb: 'https://images.unsplash.com/photo-1537640538966-79f369143f8f?auto=format&fit=crop&w=400&q=80',
    shortDescription: 'Thompson Seedless and Sharad grapes from Nashik vineyards.',
    description: 'Thompson Seedless and Sharad varieties from the Nashik belt, hand-selected bunches packed in punnets within vented export cartons.',
    specifications: ['Hand-selected bunches', 'Punnet packing within vented cartons'],
    origin: 'Nashik, Maharashtra',
    packaging: 'Punnets in 4.5–8.2 kg vented cartons',
    availability: 'Seasonal (main window Feb–Apr)',
    keywords: ['grapes', 'thompson seedless', 'sharad', 'grape exporter india']
  },
  {
    id: 'banana',
    slug: 'banana',
    name: 'Banana',
    category: 'Fruits',
    tag: 'Year round',
    image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=1000&q=85',
    thumb: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80',
    shortDescription: 'Export-grade G9 Cavendish bananas packed at controlled maturity.',
    description: 'Grand Naine (G9) Cavendish bananas harvested at controlled maturity, washed, graded by hand count and packed in poly-lined cartons for reefer shipment.',
    specifications: ['Graded by hand count per box', 'Poly-lined export cartons', 'Controlled-maturity harvest'],
    origin: 'Maharashtra & Gujarat growers',
    packaging: '13.5 / 18.5 kg poly-lined cartons',
    availability: 'Year round',
    keywords: ['banana', 'g9', 'cavendish', 'banana exporter india']
  },
  {
    id: 'basmati-rice',
    slug: 'basmati-rice',
    name: '1121 Basmati Rice',
    category: 'Rice',
    tag: 'Export grade',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=1000&q=85',
    thumb: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=400&q=80',
    shortDescription: 'Long-grain 1121 basmati — steam, sella and raw, milled to order.',
    description: '1121 traditional basmati in steam, golden sella, white sella and raw forms, milled and sortex-cleaned at certified mills with average grain length above 8.3 mm. Private-label packing available.',
    specifications: ['Average grain length 8.3 mm+', 'Steam / sella / raw forms', 'Sortex cleaned', 'Private-label packing available'],
    origin: 'Certified Indian Mills',
    packaging: '5–50 kg PP / non-woven / jute bags',
    availability: 'Year round',
    keywords: ['1121 basmati', 'basmati', 'sella', 'steam basmati', 'rice exporter india', 'basmati rice exporter']
  },
  {
    id: 'non-basmati-rice',
    slug: 'non-basmati-rice',
    name: 'Non-Basmati Rice',
    category: 'Rice',
    tag: 'Bulk supply',
    image: 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?auto=format&fit=crop&w=1000&q=85',
    thumb: 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?auto=format&fit=crop&w=400&q=80',
    shortDescription: 'Sona Masoori, IR-64 and other long-grain varieties for bulk buyers.',
    description: 'Sona Masoori, IR-64, Ponni and other non-basmati long-grain varieties for wholesale and institutional buyers, available in bulk liner or bagged form.',
    specifications: ['Sona Masoori / IR-64 / Ponni', '5% / 25% broken options', 'Bulk or bagged supply'],
    origin: 'Certified Indian Mills',
    packaging: '25 / 50 kg bags, jumbo bags or bulk liner',
    availability: 'Year round',
    keywords: ['sona masoori', 'ir64', 'ponni', 'non basmati', 'bulk rice']
  },
  {
    id: 'toor-dal',
    slug: 'toor-dal',
    name: 'Toor Dal',
    category: 'Pulses & Dals',
    tag: 'Pantry staples',
    image: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=1000&q=85',
    thumb: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=400&q=80',
    shortDescription: 'Machine-cleaned, unpolished toor dal with consistent moisture.',
    description: 'Unpolished, machine-cleaned toor (arhar) dal with consistent moisture and purity, supplied in poly-lined bags for wholesale and packing houses.',
    specifications: ['Unpolished, machine cleaned', 'Moisture as per contract', 'Poly-lined packing'],
    origin: 'Central & Western India',
    packaging: '25 / 50 kg PP bags, poly-lined',
    availability: 'Year round',
    keywords: ['toor dal', 'arhar dal', 'pigeon peas', 'dal exporter india']
  },
  {
    id: 'chickpeas',
    slug: 'chickpeas',
    name: 'Chickpeas',
    category: 'Pulses & Dals',
    tag: 'Pantry staples',
    image: 'https://images.unsplash.com/photo-1615485500704-8e990f9900f7?auto=format&fit=crop&w=1000&q=85',
    thumb: 'https://images.unsplash.com/photo-1615485500704-8e990f9900f7?auto=format&fit=crop&w=400&q=80',
    shortDescription: 'Kabuli and desi chickpeas, cleaned and graded by seed size.',
    description: 'Kabuli (42–46 count) and desi chickpeas, machine-cleaned and graded by seed size, suitable for canning, flour milling and direct packing.',
    specifications: ['Kabuli 42–46 count / desi grade', 'Machine cleaned and graded by size'],
    origin: 'Central & Western India',
    packaging: '25 / 50 kg PP bags, jumbo bags on request',
    availability: 'Year round',
    keywords: ['chickpeas', 'kabuli chana', 'desi chana', 'garbanzo', 'chana exporter india']
  },
  {
    id: 'turmeric',
    slug: 'turmeric',
    name: 'Turmeric',
    category: 'Spices',
    tag: 'Made to order',
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=1000&q=85',
    thumb: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=400&q=80',
    shortDescription: 'Turmeric fingers and powder with declared curcumin content.',
    description: 'Whole turmeric fingers and ground turmeric powder with declared curcumin content, sourced from direct processors with lot-wise documentation.',
    specifications: ['Fingers and ground powder', 'Curcumin content as declared per lot'],
    origin: 'Direct Agro Processors',
    packaging: '25 / 50 kg bags',
    availability: 'Year round',
    keywords: ['turmeric', 'haldi', 'curcumin', 'turmeric exporter india']
  },
  {
    id: 'red-chilli',
    slug: 'red-chilli',
    name: 'Red Chilli',
    category: 'Spices',
    tag: 'Made to order',
    image: 'https://images.unsplash.com/photo-1583119912267-cc97c911e416?auto=format&fit=crop&w=1000&q=85',
    thumb: 'https://images.unsplash.com/photo-1583119912267-cc97c911e416?auto=format&fit=crop&w=400&q=80',
    shortDescription: 'Whole dried red chillies and powder with declared ASTA colour.',
    description: 'Whole dried red chillies and ground powder with declared ASTA colour value, available with stemless and with-stem grades from direct processors.',
    specifications: ['With-stem and stemless grades', 'Declared ASTA colour value'],
    origin: 'Direct Agro Processors',
    packaging: '25 kg bags, compressed bales for whole chilli',
    availability: 'Year round',
    keywords: ['red chilli', 'chilli powder', 'asta', 'chilli exporter india']
  },
  {
    id: 'cumin-coriander',
    slug: 'cumin-coriander',
    name: 'Cumin & Coriander Seeds',
    category: 'Spices',
    tag: 'Made to order',
    image: 'https://images.unsplash.com/photo-1532336414038-cf19250c5757?auto=format&fit=crop&w=1000&q=85',
    thumb: 'https://images.unsplash.com/photo-1532336414038-cf19250c5757?auto=format&fit=crop&w=400&q=80',
    shortDescription: 'Sortex-cleaned cumin and coriander seeds, whole or ground.',
    description: 'Sortex-cleaned cumin and coriander seeds supplied whole or ground, with purity and admixture levels as per contract.',
    specifications: ['Sortex cleaned', 'Purity / admixture as per contract'],
    origin: 'Direct Agro Processors',
    packaging: '25 / 50 kg bags',
    availability: 'Year round',
    keywords: ['cumin', 'jeera', 'coriander seeds', 'dhania', 'spice exporter india']
  },
  {
    id: 'sugar',
    slug: 'sugar',
    name: 'Sugar',
    category: 'Other Agro Products',
    tag: 'Bulk supply',
    image: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=1000&q=85',
    thumb: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=400&q=80',
    shortDescription: 'Refined and raw sugar from Indian mills for bulk buyers.',
    description: 'Refined S-30 / M-30 and raw sugar from Indian mills, arranged for bulk buyers with mill documentation and buyer-specified packing.',
    specifications: ['S-30 / M-30 refined grades', 'ICUMSA as per mill spec'],
    origin: 'Indian Sugar Mills',
    packaging: '50 kg bags or jumbo bags',
    availability: 'Year round (mill-dependent)',
    keywords: ['sugar', 's30', 'm30', 'icumsa', 'sugar exporter india']
  },
  {
    id: 'oilseeds',
    slug: 'oilseeds',
    name: 'Oilseeds',
    category: 'Other Agro Products',
    tag: 'Bulk supply',
    image: 'https://images.unsplash.com/photo-1506368249639-73a05d6f6488?auto=format&fit=crop&w=1000&q=85',
    thumb: 'https://images.unsplash.com/photo-1506368249639-73a05d6f6488?auto=format&fit=crop&w=400&q=80',
    shortDescription: 'Groundnut, sesame and mustard seeds from direct aggregators.',
    description: 'Groundnut (bold and java), sesame and mustard seeds sourced from direct aggregators, cleaned and graded for crushing or food use.',
    specifications: ['Groundnut bold / java grades', 'Cleaned and graded seeds'],
    origin: 'Direct Aggregators',
    packaging: '25 / 50 kg bags, jumbo bags',
    availability: 'Year round (crop-dependent)',
    keywords: ['groundnut', 'sesame', 'mustard', 'oilseeds exporter india']
  }
];

if (typeof window !== 'undefined') {
  window.PRODUCTS_DATA = PRODUCTS_DATA;
  window.PRODUCT_CATEGORIES = CATEGORIES;
}
